name: Test catfact action 

on:
  push:
    main:

jobs:
  cat-fact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat