name: Test python docker action
on:
  push:
    main:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: python docker action test
        uses: .github/actions/python-docker-action
        with:
          name: David
