name: Test python docker action
on:
  push:
    main:
jobs:
  test-python-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: python docker action test
        uses: ./.github/actions/python-docker-action
        with:
          name: David
  
  cat-fact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat
